red_ball: [-5.41, 2.48, 'F']
green_ball: [-4.9, -0.533, 'F']
blue_ball: [-0.169, 8.21, 'F']
black_ball: [5.48, 2.43, 'F']
magenta_ball: [3.53, -2.64, 'F']
yellow_ball: [5.41, -6.47, 'F']
rooms: ['red_ball', 'green_ball', 'blue_ball', 'black_ball', 'magenta_ball', 'yellow_ball']
