
Closet: [-5.41, 2.48, 'F', red_ball]
LivingRoom: [-4.9, -0.533, 'F', green_ball]
Entrance: [-0.169, 8.21, 'F', blue_ball]
Bedroom: [5.48, 2.43, 'F', black_ball]
Bathroom: [5.48, 2.43, 'F', magenta_ball]
Kitchen: [5.41, -6.47, 'F', yellow_ball]
rooms: ['Closet', 'LivingRoom', 'Entrance', 'Bedroom', 'Bathroom', 'Kitchen']
playPose: [-5, 8]
