(cl:defpackage exp_assignment3-msg
  (:use )
  (:export
   "<NUM>"
   "NUM"
   "<PLANNINGACTION>"
   "PLANNINGACTION"
   "<PLANNINGACTIONFEEDBACK>"
   "PLANNINGACTIONFEEDBACK"
   "<PLANNINGACTIONGOAL>"
   "PLANNINGACTIONGOAL"
   "<PLANNINGACTIONRESULT>"
   "PLANNINGACTIONRESULT"
   "<PLANNINGFEEDBACK>"
   "PLANNINGFEEDBACK"
   "<PLANNINGGOAL>"
   "PLANNINGGOAL"
   "<PLANNINGRESULT>"
   "PLANNINGRESULT"
  ))

